### ISSUE TITLE
Parameterized the skip dirnames in test-kustomize-build

### ISSUE THREAD

**Issue by harshad16** [operate-first/toolbox#16]
It would be a good feature to have parametrized skip dirnames in the test-kustomize-build

_Originally posted by @harshad16 in https://github.com/operate-first/toolbox/pull/13#discussion_r584987846_

**Comment by tumido** [comment]
What about we do a naive scoping instead - pass the script commit hashes or commit range that should be checked and let the script decide what to check similarly to what pre-commit does.
