### ISSUE TITLE
RFE: Kustomize plugin for ACM cluster provisioning spec

### ISSUE THREAD

**Issue by tumido** [operate-first/toolbox#24]
Consolidating https://github.com/open-infrastructure-labs/ops-issues/issues/38 into a RFE here

> Not entirely sure if I understand what's going on here -- but could writing a simple exec plugin for kustomize help with this? one that maybe we could share with others who want to do the same thing?
>
_Originally posted by @HumairAK in https://github.com/open-infrastructure-labs/ops-issues/issues/38#issuecomment-804899376_

> That's a neat idea! Like ACM generator plugin.. that would work nicely. @HumairAK do you know if it's possible to compose kustomize plugins - like to use ksops generator first and then some other plugin on the same resource?  Because we probably want the resource to be encrypted in git and then decrypt and generate configs from it...

_Originally posted by @tumido in https://github.com/open-infrastructure-labs/ops-issues/issues/38#issuecomment-804906082_

> Ideally I would like to see this fixed in ACM itself :). 
>
> I think we could work around this with an exec plugin: we would probably need something that takes a single input document and uses it to generate both the ClusterDeployment resource and the `install-config.yaml` secret. If there's no "official" support for composing plugins, we can just call the ksops exec plugin ourselves, right? Or just `sops -d`, I guess.

_Originally posted by @larsks in https://github.com/open-infrastructure-labs/ops-issues/issues/38#issuecomment-805182582_

> So, just thinking about this, if we want to DRY everything out, we'll need to read as input and emit in the appropriate places...
> 
> - The pull secret (which is used both in the provider connection and in `install-config.yaml`)
> - The baremetal host information (which is used in the `ClusterDeployment` resource and in `install-config.yaml`)
> - The ssh private key (used in the provider connection and in a secret referenced by the `ClusterDeployment`...twice)
> - The ssh public key (used in the provider connection)
> - The host key for the provisioner (used in the `ClusterDeployment` and in the provider connection
> 
> I think our deployment would end up looking like:
> 
> - a `kustomization.yaml` file with maybe (a) a namespace resource and (b) a generator
> - a generator configuration that contains all the necessary input data
> 
> And that's it. And the entire configuration would then be generated by the kustomize plugin.

_Originally posted by @larsks in https://github.com/open-infrastructure-labs/ops-issues/issues/38#issuecomment-805270834_

**Comment by larsks** [comment]
https://github.com/operate-first/example-acm-install is an example of the configuration inputs necessary to drive a bare metal install using ACM.
