### ISSUE TITLE
verify aicoe-ci can build this image

### ISSUE THREAD

**Issue by goern** [operate-first/toolbox#4]
thx! :)

**Comment by harshad16** [comment]
This repository is configured wih aicoe-ci.
Tag-release is being used for the image builds.

Is the question more directed towards, kebechet? due to a lack of changelog?

**Comment by goern** [comment]
Ja

**Comment by harshad16** [comment]
i can send in the template and configuration file required.
can you install the khebhut app in this repo?

**Comment by harshad16** [comment]
@durandom @HumairAK i have requested permission to install khebhut app to the operate-first.
if someone can accept it, it would be helpful in creating release and changelogs.

**Comment by HumairAK** [comment]
@harshad16 is this for the git organization? afaik only @durandom  and @goern  have the sufficient permissions to do this.

**Comment by harshad16** [comment]
yes, it is for the operate-first org.
and you are write only owners can accept it. @goern  and @durandom please accept the request of configuring khebhut for operate-first.

**Comment by HumairAK** [comment]
@durandom  is on pto, @goern  can you do it please?

**Comment by HumairAK** [comment]
@harshad16  I accepted the request and looks like it's installed

**Comment by harshad16** [comment]
IIRC the aicoe-ci is building these images.
closing the issue.
Please feel free to open a new one and assign me, if felt otherwise.
