### ISSUE TITLE
The build check does not succeed

### ISSUE THREAD

**Issue by Gregory-Pereira** [operate-first/toolbox#67]
**Describe the bug**
The `operate-first/toolbox` image depends on the `k8s_prow/label_sync` among others, and running this container requires a `label.md` or `labels.yaml` file for configuration. Because of this, our image currently fails to build in the Dockerfile [here](https://github.com/operate-first/toolbox/blob/master/Dockerfile#L39).

**To Reproduce**
1.  Simply attempt to build the container locally, or create a PR and the build-check will fire.

**Expected behavior**
The container should be buildable from the Dockerfile.

**Comment by harshad16** [comment]
closing this issue
as the build check is working in newer pr: https://github.com/operate-first/toolbox/pull/78
